package motionspeak.csc212.motionspeak;

import android.app.Activity;
import android.content.Context;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.media.AudioManager;
import android.media.MediaRecorder;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import java.io.File;
import java.util.Timer;
import java.util.TimerTask;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p/>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class MainActivity extends Activity implements SensorEventListener {

    private Timer timer;
    private SensorManager mSensorManager;
    private Sensor mSensor;
    private float mPrevMagField;
    private float mMagField;
    private float baseValue;
    private boolean baseValueBoolean = false;
    private float[] mPrevMagValues = new float[3];

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    private CardScrollView mCardScroller;

    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    private View mView;

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        mView = buildView();

        mSensorManager = (SensorManager) getSystemService(Context.SENSOR_SERVICE);


        if (mSensorManager.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD) != null) {
            mSensor = mSensorManager.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD);
        }

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });
        // Handle the TAP event.
        mCardScroller.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Plays disallowed sound to indicate that TAP actions are not supported.
                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                am.playSoundEffect(Sounds.DISALLOWED);
            }
        });
        setContentView(mCardScroller);

    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
        mSensorManager.registerListener(this, mSensor, SensorManager.SENSOR_DELAY_NORMAL);
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
        mSensorManager.unregisterListener(this);
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private View buildView() {
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);


        timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {

                Log.d("MainActivity", "Magnetic Field is : " + mMagField);
                Log.d("MainActivity", "Base Value is : " + baseValue);
                if (mMagField > (baseValue + 15) || mMagField < (baseValue - 15)) {
                    Log.d("MainActivity", "YOU ARE MOVING");
                }
                if (baseValueBoolean == false && mMagField != 0.0) {
                    baseValue = mMagField;
                    baseValueBoolean = true;
                }
                updatePrevMagValues(mMagField);
                Log.d("MainActivity", "mPrevMagValues[0] is: " + mPrevMagValues[0]);
                Log.d("MainActivity", "mPrevMagValues[1] is: " + mPrevMagValues[1]);
                Log.d("MainActivity", "mPrevMagValues[2] is: " + mPrevMagValues[2]);
                numInRange();

            }
        }, 0, 500);

        card.setText(R.string.hello_world);
        updateCard(card);
        return card.getView();
    }

    @Override
    public final void onAccuracyChanged(Sensor sensor, int accuracy) {
        //Do something I guess if the accuracy changes
    }

    @Override
    public final void onSensorChanged(SensorEvent event) {
        //Light sensors returns a single value, some return 3 values (for each axis)
        mPrevMagField = mMagField;
        mMagField = event.values[0];

    }

    public void updateCard(CardBuilder card) {
        card.setText("The value of the magnetic field is : " + mMagField);
    }

    public void updatePrevMagValues(float mf) {

        mPrevMagValues[2] = mPrevMagValues[1];
        mPrevMagValues[1] = mPrevMagValues[0];
        mPrevMagValues[0] = mf;

    }

    public void numInRange() {
        int maxIndex = getMaxIndex();
        int index1, index2;
        if (maxIndex == 0) {
            index1 = 1;
            index2 = 2;
        } else if (maxIndex == 1) {
            index1 = 0;
            index2 = 2;
        } else {
            index1 = 0;
            index2 = 1;
        }

        if (mPrevMagValues[maxIndex] > 0) {
            if (mPrevMagValues[maxIndex] - mPrevMagValues[index1] <= 5 && mPrevMagValues[maxIndex] - mPrevMagValues[index2] <= 5) {
                baseValue = mPrevMagValues[2];
            }
        } else if (mPrevMagValues[maxIndex] < 0) {
            if (mPrevMagValues[maxIndex] - mPrevMagValues[index1] >= -5 && mPrevMagValues[maxIndex] - mPrevMagValues[index2] >= -5) {
                baseValue = mPrevMagValues[2];
            }
        }
    }

    public int getMaxIndex() {
        int maxIndex;
        if (Math.max(mPrevMagValues[0], mPrevMagValues[1]) == mPrevMagValues[0]) {
            maxIndex = 0;
        } else {
            maxIndex = 1;
        }
        if (Math.max(mPrevMagValues[maxIndex], mPrevMagValues[2]) == mPrevMagValues[2]) {
            maxIndex = 2;
        }
        return maxIndex;
    }


}
